services:
  postgres:
    image: postgres:16
    container_name: postgres_db_catalog
    restart: always
    environment:
      POSTGRES_PASSWORD: 'catalog_sol'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
